services:

  auction-backend-huseinovic:
    container_name: auction-backend-huseinovic
    build: ./  # Percorso della cartella backend
    command: nodemon --watch . -e js ./app/app.js  # Avvia l'applicazione con nodemon
    ports:
      - "3000:3000"  # Esponi la porta 5001 per il backend
    volumes:
      - ./server:/usr/src/auctionapp  # Monta la cartella backend
    depends_on:
      - mongo_auction_huseinovic # Il backend dipende dal database MongoDB
    environment: 
      - MONGODB_URI=mongodb://mongo_auction_huseinovic:27017

  mongo_auction_huseinovic:
    container_name: mongo_auction_huseinovic
    image: mongo:latest  # Usa l'immagine più recente di MongoDB
    volumes:
      - ./data:/data/db  # Mappa i dati di MongoDB per la persistenza
    ports:
      - "27017:27017"  # Porta standard di MongoDB