services:

  auction-backend-huseinovic:
    container_name: auction-backend-huseinovic
    build: ./ 
    command: node server/app.js  
    ports:
      - "3000:3000"  
    depends_on:
      - mongo_auction_huseinovic 
    environment: 
      - MONGODB_URI=mongodb://mongo-auction-huseinovic:27017

  mongo_auction_huseinovic:
    container_name: mongo-auction-huseinovic
    image: mongo:latest  
    volumes:
      - ./data:/data/db 
      - ./server/app/db/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_DATABASE: db